-- Seed: Chemistry Grades 10-12 Experiments
-- Sayansi Yathu Virtual Science Lab
USE sayansi_yathu;

INSERT INTO experiments (title, subject, subject_area, topic, experiment_code, description, difficulty_level, simulation_type, curriculum, grade_or_form, estimated_duration, apparatus, expected_outcome, safety_precautions, teacher_notes) VALUES

-- GRADE 10
('Model Construction of Atomic Structure', 'chemistry', 'Atomic Structure', 'Atoms and Elements', 'CHE-G10-001',
 'Demonstrate arrangement of electrons in shells for different elements.',
 'beginner', '3d_atom_builder', 'old', 'Grade 10', 40,
 'Atomic model kit, charts, beads',
 'Learners understand electronic configuration of elements.',
 'Handle model kits carefully. Do not swallow small beads.',
 'Ensure learners can draw electron shell diagrams before simulation.'),

('Formation of Ionic Bonds', 'chemistry', 'Chemical Bonding', 'Ionic Bonding', 'CHE-G10-002',
 'Demonstrate electron transfer between atoms to form ionic bonds.',
 'beginner', 'bond_formation', 'old', 'Grade 10', 35,
 'Atomic models, charts',
 'Formation of cations and anions observed clearly.',
 'No hazardous materials. Supervise model use.',
 'Relate to real compounds like NaCl and MgO.'),

('Formation of Covalent Bonds', 'chemistry', 'Chemical Bonding', 'Covalent Bonding', 'CHE-G10-003',
 'Demonstrate sharing of electrons to form covalent bonds.',
 'beginner', 'molecular_builder', 'old', 'Grade 10', 35,
 'Molecular model kits',
 'Learners understand covalent structures like H2O, CH4, NH3.',
 'No hazardous materials. Handle models with care.',
 'Compare single, double and triple bonds using models.'),

('Comparing Ionic and Covalent Compounds', 'chemistry', 'Chemical Bonding', 'Properties of Compounds', 'CHE-G10-004',
 'Investigate physical properties of ionic and covalent compounds.',
 'intermediate', 'compound_analyzer', 'old', 'Grade 10', 45,
 'Salt, sugar, conductivity tester, heat source',
 'Ionic and covalent compounds clearly differentiated by properties.',
 'Take care with heat source. Use low voltage for conductivity tests.',
 'Compare melting points, solubility and conductivity.'),

('Deducing Valency of Elements', 'chemistry', 'Chemical Formulae', 'Valency', 'CHE-G10-005',
 'Determine valency of elements from their compounds.',
 'beginner', 'formula_builder', 'old', 'Grade 10', 30,
 'Charts, periodic table, formula cards',
 'Accurate determination of valency from compound formulas.',
 'No hazardous materials.',
 'Use the criss-cross rule to derive formulas from valencies.'),

('Formulating and Balancing Chemical Equations', 'chemistry', 'Chemical Reactions', 'Equations', 'CHE-G10-006',
 'Balance chemical equations correctly using inspection method.',
 'intermediate', 'equation_balancer', 'old', 'Grade 10', 40,
 'Equation cards, charts',
 'Conservation of matter demonstrated through balanced equations.',
 'No hazardous materials.',
 'Stress that atoms are conserved, not created or destroyed.'),

('Investigation of Metallic Conductivity', 'chemistry', 'Metallic Bonding', 'Metals', 'CHE-G10-007',
 'Demonstrate electrical and thermal conductivity of metals.',
 'beginner', 'conductivity_sim', 'old', 'Grade 10', 35,
 'Metal rods, bulb, battery, heat source',
 'Metals conduct heat and electricity effectively.',
 'Use low voltage. Take care with heated metals.',
 'Compare conductivity of copper, iron and aluminium.'),

('Properties of Graphite and Diamond', 'chemistry', 'Macromolecules', 'Carbon Structures', 'CHE-G10-008',
 'Compare structures and properties of graphite and diamond.',
 'intermediate', 'crystal_viewer', 'old', 'Grade 10', 40,
 'Graphite sample, diamond images, molecular models',
 'Structural differences explain different physical properties.',
 'Diamond is extremely hard. Handle models carefully.',
 'Relate structure to bonding and explain why graphite conducts.'),

-- GRADE 11
('Testing Acids and Bases Using Indicators', 'chemistry', 'Acids and Bases', 'Indicators and pH', 'CHE-G11-001',
 'Identify acidic and alkaline substances using indicators.',
 'beginner', 'indicator_lab', 'old', 'Grade 11', 35,
 'Litmus paper, universal indicator, various solutions',
 'Substances correctly classified by pH using indicators.',
 'Avoid contact with concentrated acids/bases. Wear eye protection.',
 'Include household substances like lemon juice and soap.'),

('Determining pH of Solutions', 'chemistry', 'Acids and Bases', 'pH Scale', 'CHE-G11-002',
 'Measure pH values of solutions accurately.',
 'beginner', 'ph_meter_sim', 'old', 'Grade 11', 30,
 'pH meter, indicators, various solutions',
 'Accurate pH determination of solutions.',
 'Handle pH meter probe carefully. Rinse between measurements.',
 'Calibrate pH meter before use. Cross-check with indicators.'),

('Reactions of Acids with Metals and Carbonates', 'chemistry', 'Acids and Bases', 'Acid Reactions', 'CHE-G11-003',
 'Observe characteristic reactions of acids with metals and carbonates.',
 'intermediate', 'reaction_observation', 'old', 'Grade 11', 45,
 'Dilute HCl, dilute H2SO4, metals (Zn, Mg), calcium carbonate',
 'Hydrogen and carbon dioxide gas production observed.',
 'Dilute acids only. Wear goggles. No mouth pipetting.',
 'Test gases produced using splint and limewater.'),

('Preparation of Insoluble Salts', 'chemistry', 'Salts', 'Salt Preparation', 'CHE-G11-004',
 'Prepare insoluble salts by precipitation reaction.',
 'intermediate', 'precipitation_lab', 'old', 'Grade 11', 45,
 'Silver nitrate solution, sodium chloride solution, filter paper, funnel',
 'Insoluble salt (silver chloride) formed and filtered successfully.',
 'Silver nitrate stains skin. Wear gloves and goggles.',
 'Discuss ionic equation for precipitation reactions.'),

('Preparation of Soluble Salts by Crystallisation', 'chemistry', 'Salts', 'Crystallization', 'CHE-G11-005',
 'Prepare soluble salts by neutralisation and crystallisation.',
 'intermediate', 'crystallization_sim', 'old', 'Grade 11', 50,
 'Dilute acid, alkali, evaporating dish, heat source, filter paper',
 'Pure crystals of the salt formed successfully.',
 'Take care with hot solutions. Use tongs for hot evaporating dish.',
 'Use copper oxide and sulphuric acid for copper sulphate crystals.'),

('Acid-Base Titration', 'chemistry', 'Quantitative Chemistry', 'Titration', 'CHE-G11-006',
 'Determine concentration of a solution by acid-base titration.',
 'advanced', 'titration', 'old', 'Grade 11', 60,
 'Burette, pipette, conical flask, indicator, sodium hydroxide, hydrochloric acid',
 'Accurate concentration of unknown solution calculated.',
 'Dilute solutions only. Read burette at eye level. Wear goggles.',
 'Discuss endpoint vs equivalence point. Repeat for concordant results.'),

('Identification of Cations and Anions', 'chemistry', 'Qualitative Analysis', 'Ion Identification', 'CHE-G11-007',
 'Identify ions in solution using chemical tests.',
 'advanced', 'qualitative_analysis', 'old', 'Grade 11', 55,
 'Sodium hydroxide solution, ammonia solution, test solutions, test tubes',
 'Correct ions identified from precipitate colours and observations.',
 'NaOH and ammonia are caustic. Wear gloves and goggles.',
 'Prepare reference table of expected results for each ion.'),

('Identification of Gases', 'chemistry', 'Qualitative Analysis', 'Gas Tests', 'CHE-G11-008',
 'Test and identify common laboratory gases.',
 'intermediate', 'gas_test_sim', 'old', 'Grade 11', 40,
 'Gas jars, burning splint, damp litmus paper, limewater',
 'Gases correctly identified using standard tests.',
 'Ensure good ventilation. No open flames near hydrogen.',
 'Cover H2, O2, CO2, Cl2, NH3, SO2 gas tests.'),

('Investigating Factors Affecting Reaction Rates', 'chemistry', 'Chemical Reactions', 'Rates of Reaction', 'CHE-G11-009',
 'Determine the effect of temperature, concentration and surface area on reaction rate.',
 'advanced', 'reaction_rate_sim', 'old', 'Grade 11', 55,
 'Marble chips, dilute hydrochloric acid, stopwatch, balance',
 'Reaction rates change with temperature, concentration and surface area.',
 'Dilute acid only. Take care with hot solutions.',
 'Plot rate vs time graphs. Discuss collision theory.'),

('Endothermic and Exothermic Reactions', 'chemistry', 'Energetics', 'Energy Changes', 'CHE-G11-010',
 'Observe and measure temperature changes during chemical reactions.',
 'intermediate', 'energy_change_sim', 'old', 'Grade 11', 40,
 'Thermometer, chemicals (citric acid, sodium bicarbonate, calcium chloride), beakers',
 'Heat absorbed (endothermic) or released (exothermic) clearly observed.',
 'Do not heat concentrated chemicals directly.',
 'Plot temperature-time graphs and classify reactions.'),

('Redox Reactions and Oxidation Numbers', 'chemistry', 'Redox Chemistry', 'Oxidation and Reduction', 'CHE-G11-011',
 'Determine oxidation and reduction in redox reactions.',
 'advanced', 'redox_analyzer', 'old', 'Grade 11', 50,
 'Potassium permanganate, iron(II) sulphate, dilute sulphuric acid',
 'Redox processes clearly identified by colour changes.',
 'KMnO4 is an oxidising agent. Wear gloves and goggles.',
 'Use oxidation number changes to identify oxidising/reducing agents.'),

('Investigating Chemical Equilibrium', 'chemistry', 'Equilibrium', 'Reversible Reactions', 'CHE-G11-012',
 'Observe the effects of changing conditions on chemical equilibrium.',
 'advanced', 'equilibrium_sim', 'old', 'Grade 11', 55,
 'Equilibrium setup, heating apparatus, concentrated HCl, cobalt chloride solution',
 'Equilibrium shifts observed when concentration and temperature change.',
 'Cobalt compounds may be irritants. Use in a fume cupboard.',
 'Demonstrate Le Chatelier''s principle with colour changes.'),

-- GRADE 12
('Testing Conductors and Non-Conductors', 'chemistry', 'Chemistry and Electricity', 'Conductivity', 'CHE-G12-001',
 'Classify materials as conductors or insulators using an electrical circuit.',
 'beginner', 'conductivity_tester', 'old', 'Grade 12', 35,
 'Battery, bulb, connecting wires, various substances',
 'Conductors and non-conductors correctly identified.',
 'Use low voltage batteries only. Ensure no short circuits.',
 'Test both ionic solutions and solid metals to compare.'),

('Electrolysis of Molten Lead Bromide', 'chemistry', 'Electrolysis', 'Electrolytic Cells', 'CHE-G12-002',
 'Observe decomposition of molten lead bromide by electricity.',
 'advanced', 'electrolysis_sim', 'old', 'Grade 12', 55,
 'Electrolysis cell, carbon electrodes, molten lead bromide, power supply',
 'Lead deposited at cathode; bromine vapour produced at anode.',
 'Lead compounds are toxic. Bromine is toxic. Use fume cupboard. Wear full PPE.',
 'Relate products to position of ions and electrode type.'),

('Electrolysis of Copper Sulphate Solution', 'chemistry', 'Electrolysis', 'Electrolysis of Aqueous Solutions', 'CHE-G12-003',
 'Identify products at electrodes during electrolysis of copper sulphate solution.',
 'advanced', 'electroplating_sim', 'old', 'Grade 12', 55,
 'Copper sulphate solution, copper electrodes, power supply, balance',
 'Copper deposited at cathode; anode loses mass.',
 'Copper sulphate is toxic. Wear gloves and goggles.',
 'Weigh electrodes before and after. Discuss industrial electroplating.'),

('Construction of a Simple Chemical Cell', 'chemistry', 'Electrochemistry', 'Simple Cells', 'CHE-G12-004',
 'Generate electricity using chemical reactions in a simple cell.',
 'intermediate', 'cell_builder_sim', 'old', 'Grade 12', 45,
 'Zinc strip, copper strip, electrolyte (dilute H2SO4 or salt solution), voltmeter',
 'Electricity produced chemically; voltage recorded on voltmeter.',
 'Dilute acid only. No short circuits.',
 'Compare cells with different metal combinations and electrolytes.'),

('Determining the Reactivity Series of Metals', 'chemistry', 'Metals', 'Reactivity Series', 'CHE-G12-005',
 'Arrange metals in order of reactivity using displacement reactions.',
 'intermediate', 'reactivity_comparator', 'old', 'Grade 12', 45,
 'Metal strips (Zn, Fe, Cu, Mg), metal salt solutions',
 'Reactivity order of metals determined from displacement reactions.',
 'Some metal solutions are toxic. Wear gloves.',
 'Build reactivity series table from observations.'),

('Thermal Decomposition of Metal Salts', 'chemistry', 'Metals', 'Effects of Heat on Salts', 'CHE-G12-006',
 'Observe decomposition of metal salts by heating.',
 'intermediate', 'thermal_decomp_lab', 'old', 'Grade 12', 45,
 'Test tubes, Bunsen burner, metal salts (nitrates and carbonates)',
 'Different decomposition behaviours observed for different salts.',
 'Hot test tubes cause burns. Use tongs. Ensure good ventilation.',
 'Relate decomposition temperature to position in reactivity series.'),

('Investigation of Corrosion and Rust Prevention', 'chemistry', 'Metals', 'Corrosion', 'CHE-G12-007',
 'Study the conditions required for rusting and evaluate prevention methods.',
 'intermediate', 'corrosion_sim', 'old', 'Grade 12', 50,
 'Iron nails, test tubes, water, oil, anhydrous calcium chloride, paint',
 'Rusting conditions identified; prevention methods evaluated.',
 'Anhydrous CaCl2 is a desiccant — handle with care.',
 'Set up experiment one week in advance to observe results.'),

('Laboratory Preparation and Test for Hydrogen Gas', 'chemistry', 'Non-Metals', 'Hydrogen', 'CHE-G12-008',
 'Prepare hydrogen gas and confirm its identity using the burning splint test.',
 'beginner', 'gas_prep_lab', 'old', 'Grade 12', 35,
 'Zinc granules, dilute hydrochloric acid, delivery tube, test tube, burning splint',
 'Squeaky pop sound confirms presence of hydrogen gas.',
 'No naked flames near hydrogen collection. Ensure apparatus is sealed.',
 'Discuss uses of hydrogen and its position in the reactivity series.');

SELECT CONCAT('Seeded ', COUNT(*), ' Grade 10-12 chemistry experiments.') AS status
FROM experiments WHERE experiment_code LIKE 'CHE-G1%';
